# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(205, 126)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 42, 16))
        self.label_2.setObjectName("label_2")
        self.musicBtn = QtWidgets.QToolButton(Dialog)
        self.musicBtn.setGeometry(QtCore.QRect(160, 10, 26, 18))
        self.musicBtn.setObjectName("musicBtn")
        self.musicTxt = QtWidgets.QLabel(Dialog)
        self.musicTxt.setGeometry(QtCore.QRect(57, 10, 91, 18))
        self.musicTxt.setObjectName("musicTxt")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(10, 40, 175, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setGeometry(QtCore.QRect(10, 90, 175, 20))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_3 = QtWidgets.QLabel(self.splitter_2)
        self.label_3.setObjectName("label_3")
        self.phoneEdit = QtWidgets.QLineEdit(self.splitter_2)
        self.phoneEdit.setText("")
        self.phoneEdit.setObjectName("phoneEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "提示声:"))
        self.musicBtn.setText(_translate("Dialog", "..."))
        self.musicTxt.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "游戏ID:"))
        self.label_3.setText(_translate("Dialog", "手机号:"))
